name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Libs
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://github.com/EvaisaAM/Unity-Internal-Libraries/raw/master/UnityEngine.dll' -OutFile 'UnityEngine.dll'"
          powershell -Command "Invoke-WebRequest -Uri 'https://github.com/EvaisaAM/Unity-Internal-Libraries/raw/master/UnityEngine.IMGUIModule.dll' -OutFile 'UnityEngine.IMGUIModule.dll'"

      - name: Hard-coded Build
        run: |
          # 2026年のGitHub環境にあるVisual Studio 2022の標準パスを直接叩くぜ
          $csc = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
          & $csc /target:library /out:Project.dll /reference:UnityEngine.dll /reference:UnityEngine.IMGUIModule.dll ESP.cs

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: Project.dll
